name: Deploy Discord Bot

on:
  workflow_dispatch:
    inputs:
      build_image:
        description: 'Build Docker image?'
        required: false
        default: 'true'
      operation:
        description: 'Operation to perform (Install, Uninstall, Reinstall)'
        required: false
        default: 'Reinstall'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Show selected inputs
      run: |
        echo "Build image: ${{ github.event.inputs.build_image || 'true' }}"
        echo "Operation: ${{ github.event.inputs.operation || 'Reinstall' }}"
