name: Test Run Button

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
        default: 'Hello from test-run.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: |
          echo "Message value: ${{ github.event.inputs.message }}"
